#-----------------------------------------------------
# PIPELINE STAGES
#-----------------------------------------------------

stages:
  - test


#-----------------------------------------------------
# TEST: QA TEST
#-----------------------------------------------------


qa_test:
  stage: test
  only:
    - main
  variables:
    QA_ENVIRONMENT: "recette"
    WEB_DRIVER: "chrome"
  allow_failure: true
  before_script:
    - google-chrome-stable --headless --disable-gpu --print-to-pdf https://www.chromestatus.com/ --no-sandbox
  script:
    - mvn clean -Denvironment=$QA_ENVIRONMENT -DwebDriver=$WEB_DRIVER test
  after_script:
    - ps aux | grep chrome | awk ' { print $2 } ' | xargs kill -9 || true
  artifacts:
    when: always
    name: "qa_report"
    paths:
      - target/reports/*
    expire_in: 1 h
  tags:
    - gitlab-runner
