#-----------------------------------------------------
# PIPELINE STAGES
#-----------------------------------------------------


stages:
  - test

#-----------------------------------------------------
# TEST: QA TEST
#-----------------------------------------------------
qa_test:
  stage: test
  only:
    - main
  variables:
    QA_ENVIRONMENT: "recette"
    WEB_DRIVER: "chrome"
  allow_failure: true
  script:
    - echo $QA_ENVIRONMENT
    - mvn clean -Denvironment=$(echo $QA_ENVIRONMENT) -DwebDriver=$(echo $WEB_DRIVER) test
  artifacts:
    when: always
    name: "qa_report"
    paths:
      - target/reports/*
    expire_in: 1 h
  tags:
    - gitlab-runner
