#-----------------------------------------------------
# PIPELINE STAGES
#-----------------------------------------------------


stages:
  - test

#-----------------------------------------------------
# TEST: QA TEST
#-----------------------------------------------------

qa_test:
  stage: test
  variables:
    QA_ENVIRONMENT: recette
    WEB_DRIVER: chrome
  allow_failure: true
  before_script:
    - mvn install
  script:
    - mvn -Denvironment=$QA_ENVIRONMENT -DwebDriver=$WEB_DRIVER test
  tags:
    - gitlab-runner
  artifacts:
    when: always
    name: "qa_report"
    paths:
      - target/reports/*
    expire_in: 1 h