#-----------------------------------------------------
# PIPELINE STAGES
#-----------------------------------------------------

stages:
  - build
  - test
  - notify


#-----------------------------------------------------
# BUILD: QA BUILD
#-----------------------------------------------------


build_test:
  stage: build
  only:
    - main
  script:
    - chmod +x ci/build.sh
    - ./build.sh
  tags:
    - gitlab-runner


#-----------------------------------------------------
# TEST: QA TEST
#-----------------------------------------------------


qa_test:
  stage: test
  only:
    - main
  variables:
    QA_ENVIRONMENT: "recette"
    WEB_DRIVER: "chrome"
  allow_failure: true
  script:
    - chmod +x ci/test.sh
    - ./test.sh
  artifacts:
    when: always
    name: "qa_report"
    paths:
      - target/reports/report.html
    expire_in: 1 h
  tags:
    - gitlab-runner


#-----------------------------------------------------
# TEST: QA NOTIFY
#-----------------------------------------------------

qa_notify:
  stage: notify
  only:
    - main
  script:
    - chmod +x ci/notify.sh
    - ./notify.sh
  tags:
    - gitlab-runner
